//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZMChuangDianAccount
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CloudID { get; set; }
        public decimal InNum { get; set; }
        public decimal OutNum { get; set; }
        public string Operator { get; set; }
        public string TraceNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public string source { get; set; }
        public bool TRANS { get; set; }
    }
}
