//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZMCoupon
    {
        public int id { get; set; }
        public string CouponID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Denomination { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string TimeExplain { get; set; }
        public Nullable<int> Type { get; set; }
        public string UsableProducts { get; set; }
        public string UsableProductClass { get; set; }
        public string UsableProductBrand { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
