//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZMCouponRecord
    {
        public int id { get; set; }
        public string CloudID { get; set; }
        public string RoleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CouponValue { get; set; }
        public string CouponID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string UseRoleID { get; set; }
        public string OrderID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendMobile { get; set; }
    }
}
